server:
  port: 80
eureka:
  client:
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka
    register-with-eureka: false
ribbon:
  #建立连接超时时间
  ConnectTimeout: 5000
  #建立连接之后，读取响应资源超时时间
  ReadTimeout: 5000

logging:
  level:
    #feign日志以什么级别监控那个接口！
    com.lyx.services.PaymentFeignServices: debug