server:
  port: 8001
eureka:
  client:
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka
    register-with-eureka: true
    fetch-registry: true
ribbon:
  #建立连接超时时间
  ConnectTimeout: 5000
  #建立连接之后，读取响应资源超时时间
  ReadTimeout: 5000
spring:
  application:
    name: cloud-provider-hystrix-payment