server:
  port: 80
eureka:
  client:
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka
    register-with-eureka: false
#用于服务降级，在注解FeignClient中添加fallback属性值
feign:
  hystrix:
    enabled: true